MUSCLE (3.8) multiple sequence alignment


MGG_15682T0_1       ------------------------------------------------------------
MGG_14967T0_8       -----------------------------------------KQAVRLVN-----------
MGG_02611T0_2       ---------------------------------------NVDIVNMYGT-----------
MGG_14967T0_4       ---------------------------------------------LVIG-----------
MGG_05025T0_2       ------------------------------------------------------------
MGG_09647T0_2       ------------------------------------------------------------
MGG_15248T0_2       --------------------------------------DAWSACKDVYN-----------
MGG_14967T0_2       ------------------------------------------------------------
MGG_06199T0_2       ------------------------------------------------------------
MGG_08288T0_3       ------------------------------------------------------------
MGG_12175T0_6       ---------------------------------------AWGDQGVIYN-----------
MGG_14967T0_6       ---------------------------------------AWAPRIMLLN-----------
MGG_12175T0_4       -----------------------------------------------YG-----------
MGG_07858T0_3       --------------------------------------------FKLYN-----------
MGG_07803T0_2       -----------------------------------------RKRVELLH-----------
MGG_02351T0_6       ------------------------------------------------------------
MGG_00022T0_2       ------------------------------------------------------------
MGG_12175T0_2       ------------------------------------------------------------
MGG_02351T0_10      ------------------------------------------------------------
MGG_07858T0_5       ------------------------------------------DKLRLMN-----------
MGG_07858T0_7       ------------------------------------------------------------
MGG_14767T0_1       PADSAMYVIFTSGSTGVPKGVVCSHANFVSGAIPRAEAVGYGETSRVFEFASYAFDVSID
MGG_02351T0_4       ------------------------------------------------------------
MGG_02351T0_2       ------------------------------------------GRVRLVN-----------
MGG_02351T0_8       ------------------------------------------------------------
MGG_00689T0_1       ------KLVSSAKARKLPPAECVPVGSNDPIYIIYTSGTTGLPKGVVRE-----------
MGG_09647T0_1       ------------------------------------------------------------
MGG_04646T0_1       -------------YGGLLADVARVRD--RLCEASGKRELDGERVAFLVE-----------
MGG_14967T0_5       ------------------------------------------------D-----------
MGG_14967T0_1       -----------------------------------------QHVAVMLE-----------
MGG_03290T0_1       DAVALEDETTTLTYAELERQTGLLAN-----RLRQQGVGRDSLVGVLLG-----------
MGG_14967T0_7       ----------TITYSALHELAEKGAAGLALQTSTLGKTLHGERVALYLD-----------
MGG_02351T0_3       ---AVASWDRSLTYRQLRDLSEHLAY--RLLHQGGGVGPGS-LVVLNFD-----------
MGG_00022T0_1       DAIAISSWDGEWTYAQLDKVTSDLAD----HILTLGEVEVGQVVALCFE-----------
MGG_07858T0_1       ------------TYKQLDTLTDKLAH-----LLVSKRVSPGKIVPLMFE-----------
MGG_07858T0_4       ---AIESRQVTLSYQQLDDLATHMAH--QLCEL-G-AAPER-IIPISME-----------
MGG_07858T0_6       -----------------------------------------VIVPLCFE-----------
MGG_07858T0_2       ---------------------------------------------FAFE-----------
MGG_02351T0_7       ---------------------------------------RNTVVPLVFE-----------
MGG_02351T0_1       ---------------------------------------------VLFP-----------
MGG_02351T0_9       ---------------------------------------------LCFE-----------
MGG_12175T0_3       -PAAGDTQVQTISYQELNRQANRIAH--LVIGSKVMPGM---TVAIIME-----------
MGG_00022T0_4       --------------------------------------------ANLYN-----------
MGG_00022T0_3       DAIAACDSAGRMTYSELDDKSDKLAA-----WLRHRGIPAETPVGILSP-----------
MGG_00022T0_6       -ATAVTDLSYSLTYQQLDEQSDRLAS-----WLRRRHLAPEALVAVLSP-----------
MGG_03810T0_1       --------------------------------------------GMFQE-----------
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       ------------------------------------VETRGAFCALLLE-----------
MGG_09589T0_1       DAPAISDGDQTLTYCELMRKVDNICE--LLLKTKTASEDDNFVCVLLFE-----------
MGG_12175T0_5       -------------------------------------------VAILFD-----------
MGG_12447T0_1       ---------------GGLTYSQMIARINDIAAKLIDAKVGTGIVGVMQA-----------
MGG_14943T0_1       ------------------------------------------------E-----------
MGG_15097T0_1       -IAVKDGRGDRITYREMSQKIDCISH----ALSSDSSCRVKSTVGVLLD-----------
MGG_15248T0_1       ---ALEKGDRTMTYAELQTRSTAICD------VLAPVVTEGDVVCVHSD-----------
MGG_12175T0_1       ------------------------------------------IVPVLLP-----------
MGG_14967T0_3       -AAAIESASFSMTYAELDRASDRVA-----VHMLTEMDLRRGLVALFFP-----------
MGG_15681T0_1       ------------------------------------------------------------
                                                                                

MGG_15682T0_1       ------------------------------------------------------------
MGG_14967T0_8       ----------------------------------------------GYGPTEGVVI-TWK
MGG_02611T0_2       ----------------------------------------------TETSRAVSYYKIPN
MGG_14967T0_4       ----------------------------------------------AYGPTETAIQVLVS
MGG_05025T0_2       ------------------------------------------------------------
MGG_09647T0_2       ------------------------------------------------------------
MGG_15248T0_2       ----------------------------------------------MYGPTEATCGATIK
MGG_14967T0_2       ------------------------------------------------------------
MGG_06199T0_2       ------------------------------------------------------------
MGG_08288T0_3       ------------------------------------------------------------
MGG_12175T0_6       ----------------------------------------------AYGPTEATIGVTMY
MGG_14967T0_6       ----------------------------------------------VYGPTEATVDVITR
MGG_12175T0_4       ----------------------------------------------PSETTNICTVKKMK
MGG_07858T0_3       ----------------------------------------------TYGPSECSV----Q
MGG_07803T0_2       ----------------------------------------------AYGPTECTVICTLE
MGG_02351T0_6       ------------------------------------------------------------
MGG_00022T0_2       ------------------------------------------------------------
MGG_12175T0_2       ------------------------------------------------------------
MGG_02351T0_10      ------------------------------------------------------------
MGG_07858T0_5       ----------------------------------------------GYGPTETCVFCTTR
MGG_07858T0_7       ------------------------------------------------------------
MGG_14767T0_1       CMLCTLMQGGTVCVPSEAGRVDNLGAAILASGANMAHMTPSVARVLEDPETVMRSLDVLG
MGG_02351T0_4       ------------------------------------------------------------
MGG_02351T0_2       ----------------------------------------------TYGPTECTF-----
MGG_02351T0_8       ------------------------------------------------------------
MGG_00689T0_1       ----------------------------------------------SGGHAVGLYLSINS
MGG_09647T0_1       ----------------------------------------------NSVFVVILQQALMR
MGG_04646T0_1       ----------------------------------------------NSYDYVVTLLAILA
MGG_14967T0_5       ----------------------------------------------VSIERLAVLIAVMS
MGG_14967T0_1       ----------------------------------------------RSPAQVASILAIAK
MGG_03290T0_1       ----------------------------------------------RSADYVIACLAALR
MGG_14967T0_7       ----------------------------------------------KSIETVATIFAAHR
MGG_02351T0_3       ----------------------------------------------KSSWLVVCMMATLK
MGG_00022T0_1       ----------------------------------------------RSKWTVAAMLAVNK
MGG_07858T0_1       ----------------------------------------------KSVWTVVAAIAVLK
MGG_07858T0_4       ----------------------------------------------KSVNAIVAMLAVLK
MGG_07858T0_6       ----------------------------------------------KSGWAIVALLSVIK
MGG_07858T0_2       ----------------------------------------------KSAWTTVAILAILK
MGG_02351T0_7       ----------------------------------------------KSMYGMVALLSVLK
MGG_02351T0_1       ----------------------------------------------KSRWTSVAMLAVVK
MGG_02351T0_9       ----------------------------------------------KSVWYPVAALAVMR
MGG_12175T0_3       ----------------------------------------------KSISLYAGILGILK
MGG_00022T0_4       ----------------------------------------------SLGPSECCVLNVIY
MGG_00022T0_3       ----------------------------------------------RSCQTLVAMIGVLK
MGG_00022T0_6       ----------------------------------------------RACETVVAFLGVLK
MGG_03810T0_1       ----------------------------------------------PTVDWVVTMLGVWR
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       ----------------------------------------------PSADYVAALLAVFK
MGG_09589T0_1       ----------------------------------------------PSADYIAALLAVLR
MGG_12175T0_5       ----------------------------------------------KCPEAYFAILGILK
MGG_12447T0_1       ----------------------------------------------STMDFICSILAVWK
MGG_14943T0_1       ----------------------------------------------PGADWIVSLLAIWR
MGG_15097T0_1       ----------------------------------------------PSSDWICSILAILR
MGG_15248T0_1       ----------------------------------------------RSLEWICAIWGILK
MGG_12175T0_1       ----------------------------------------------QSPELYVALLAILK
MGG_14967T0_3       ----------------------------------------------RSVFMIIAMLGTLK
MGG_15681T0_1       ------------------------------------------------------------
                                                                                

MGG_15682T0_1       --------------PLSIGAPT----------------------PNNS---VY-ILDE--
MGG_14967T0_8       LCRP-------NTDGSCVGRPA----------------------MGMK---VR-ILDE--
MGG_02611T0_2       RASDPDFLERLGKDTIPAGTGM----------------------ENVQ------LLVVNR
MGG_14967T0_4       PVAG-------ARGGDDDDVVV----------------------YDAL---PG-NLVVLA
MGG_05025T0_2       ------------------------------------------------------------
MGG_09647T0_2       ------------------------------------------------------DVEIVD
MGG_15248T0_2       RLR--------SGQDVNIGRPN----------------------PSTR---VY-VLNS--
MGG_14967T0_2       ----------------VIGRPS----------------------PHAS------VMVITP
MGG_06199T0_2       -----------------------------------------------E------VRILDG
MGG_08288T0_3       --------------LTTVGRLM----------------------PHAH---AK-IVDH--
MGG_12175T0_6       QRVPR------NGRASNIGKQF----------------------LNVG------SYVFKP
MGG_14967T0_6       RCYP-------DTPISNIGRPL----------------------ANVQ---AY-IL--DD
MGG_12175T0_4       AGDVI----------QHLGFAF----------------------ENTS---SF-VVHKES
MGG_07858T0_3       STCCLEPLGR-DARGGNIGYPM----------------------NCN-------IFVVDS
MGG_07803T0_2       SLTQDESTQT-AIDATVIGKAL----------------------PNLD------IRICEE
MGG_02351T0_6       ------------------------------------------------------------
MGG_00022T0_2       -----------------------------------------------R------IWLTDP
MGG_12175T0_2       ------------------------------------------------------------
MGG_02351T0_10      ------------TRNNHVGRPY----------------------GAN-------VWLVEP
MGG_07858T0_5       DISK-------GDRAEKIGHMV----------------------SSVG-------WVVDP
MGG_07858T0_7       ---------------------------------------------------------VEA
MGG_14767T0_1       LGGEAVSAGD-AAAWSRLTKVVIAYGPSECTVGCTINHEVCADNTTIGKGTGAVTWIVHP
MGG_02351T0_4       ------------------------------------------------------------
MGG_02351T0_2       -KCAFAEIDPAQQDRPHLGMGA-----------------------------AFALWIVDP
MGG_02351T0_8       ------------------------------------------------------TWVLDP
MGG_00689T0_1       KFGIHGPGDV-MACFSDIGWVV----------------------SHSYTLYGP-LITGAA
MGG_09647T0_1       QGAIIVPLNW-RLSASEIGSLI----------------------EDCS---PK-LLFWDA
MGG_04646T0_1       AKSIAVPLAP-AFPPPELQYIL----------------------DHSE---AA-LLLSSS
MGG_14967T0_5       LGAAYIPIDL-ANPLDWNKTIV----------------------KDCD---PC-CMVFMP
MGG_14967T0_1       IGAVYVPVDH-NLPRTRVHSIV----------------------ASVE---DC-VILCDT
MGG_03290T0_1       AGGAFLVLEL-AYPPQLLCDVI----------------------DDAN---PT-VVVTHR
MGG_14967T0_7       LCATYVPLDI-ESPPSRIRDLV----------------------GSIR---PA-AVVCEL
MGG_02351T0_3       MGATALPLSS-PATTHRALEII----------------------EAVQ---PK-LVLTSG
MGG_00022T0_1       AGLAFTLVDP-SLPPARIANMC----------------------EQTS---AK-LAFTSQ
MGG_07858T0_1       AGGAFGYIEP-NQPWEDVSRLL----------------------GACE---ST-FVLCSA
MGG_07858T0_4       AGAAFVPINP-EDPQDRRADLL----------------------AQVQ---AE-IILVSP
MGG_07858T0_6       AGGAVVFLDP-SYPMARLNEIL----------------------SQIE---AK-VILCSL
MGG_07858T0_2       AGGACVALDM-SYPRSRLERIM----------------------QDVE---AK-TVLCSR
MGG_02351T0_7       AGAGVLLLDS-TLPESRLQAII----------------------TQTN---PA-VVVSSV
MGG_02351T0_1       AGCSAVALDG-TQPDSRLRSIV----------------------GQTR---PP-LVVAAA
MGG_02351T0_9       AGGACLAMDS-TQPEARLRSIV----------------------QQVG---PK-LILSSA
MGG_12175T0_3       AGCAYLPLLP-STPLQRIETIL----------------------GHSE---AA-ACLCDA
MGG_00022T0_4       ------------------------------------------------------RIDEED
MGG_00022T0_3       ANLACLPLNV-DYSTTRIKHML----------------------SSAK---LV-NTKTQP
MGG_00022T0_6       ANLAYIPLDV-NAPPGRIDTIL----------------------SCVP---GS-KLVLLG
MGG_03810T0_1       AGASYVPLDL-AQGLPRLARIA----------------------KASK---LA-ALVVHS
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       LRAVAFPMDT-TNHKQRLAVMA----------------------KDCR---PS-ILLYHN
MGG_09589T0_1       VAGVAVPIDP-RNHKERMAVMV----------------------GDCK---PT-VILHHS
MGG_12175T0_5       SGCSFVALDP-AAPAARRQFII----------------------EDSG---AS-ALVTD-
MGG_12447T0_1       AGAIYTPLDPRLNSTDRLKAVV----------------------DECQ---PA-CILVDA
MGG_14943T0_1       VGCVYMPFDA-ATPMSRIAINC----------------------AHAS---PQ-LVLVDE
MGG_15097T0_1       LGATYVPLDI-VTGWDRLSSVV----------------------RDSK---PD-LILVNN
MGG_15248T0_1       AGCTYCSLDP-QLTAAWRESMA----------------------EAVS---ATAFITATT
MGG_12175T0_1       AGGAFCPLNL-DAPPERVRFIL----------------------EDVT---AR-VVITSQ
MGG_14967T0_3       AGLAYCPIEW-EAPPARVARLL----------------------RQLN---VS-TIVSNN
MGG_15681T0_1       ------------------------------------------------------------
                                                                                

MGG_15682T0_1       --QL---------NPVPFGEPGV------MWAG--GAGVSRGY----IGLPEKT------
MGG_14967T0_8       --YM---------RPVPIGTKGL------IWCS--GRQLSLGY----FGRKDAT------
MGG_02611T0_2       EDRT---------KLCGIGEVGE------IYVR--AAGLAEGYKGDPALNEQKF------
MGG_14967T0_4       DQRG---------ELCYINEPGE------ILVA--GVQVFAGYEGEVASASQEY------
MGG_05025T0_2       ---------------VPYDEGGE------ILLRIPGERTFPGY----FNNPEAT------
MGG_09647T0_2       PETG---------APVLPGEPGE------IVAS--GMSVTAGY----WGRADRD------
MGG_15248T0_2       --SG---------GLSQPGMVGR------IHLA--GVQVSRGY----HGMPEQT------
MGG_14967T0_2       GGYA-----------AAEGTTGE------IVVK--GGSVFKGY---SNRDVHPC------
MGG_06199T0_2       DGNE-----------LPRGVEGE------ICIR--GENVTSGY----LNNAEAN------
MGG_08288T0_3       --DG---------NVVPLGRRGE------LCIA--GYQLQAGY----WNNSEKT------
MGG_12175T0_6       GTE----------IPTLRGGIGE------LCVS--GKLVGKGY----LNRKDLT------
MGG_14967T0_6       SAEL---------QQVPAGEVGQ------LALG--GVQVSPGY----LRDPPGR------
MGG_12175T0_4       RNGV---------DLVPFGCVGE------LCFG--GDQVVQGY----LGMPELT------
MGG_07858T0_3       DNPN---------VLLPGGETGE------MLIE--GPIVGRGY----LKNEDKT------
MGG_07803T0_2       GKLE---------PLAP-NQVGE------ICVV--GPQVSRGY----MGQEELT------
MGG_02351T0_6       ---D---------RLVPFGTVGE------IALE--GPLGADGY----VANDAMT------
MGG_00022T0_2       NDVG---------KLAPVGAIGE------ITVE--TPCLALGY-LPSSS-AEAR------
MGG_12175T0_2       --------------VLPVGEIGE------LVVG--GYQLAEGY----LNRPEQT------
MGG_02351T0_10      GRPD---------RLAGVGTTAE------LAIE--GPTLSSGY----FGDAAGS------
MGG_07858T0_5       QDHN---------RLVPIGCTGE------LLVQ--GPGLSRGY----LGQPDKT------
MGG_07858T0_7       ENHD---------RLAPVGTVGE------LIIE--GPTLGRGY----LKNPEKT------
MGG_14767T0_1       DDHN---------RLMPVGSVGE------LLIE--GPVVGLGY----LGQPDKT------
MGG_02351T0_4       ------------------------------------------------------------
MGG_02351T0_2       ADAT---------KLAPVGSAGE------LYLE--GPLVGQGY----LADPDKT------
MGG_02351T0_8       ASSE---------RLMPVGAVGE------LYLQ--GPLVGRGY----LGDHETT------
MGG_00689T0_1       TVLY---------EGKPVGTPDA----GAFWRIVEEYKVNSLF-----TAPTAL------
MGG_09647T0_1       TLSL---------AWPDFEPHFP------ALCQ--RLPFQDFI-TKLDQSTLPTSPVQHQ
MGG_04646T0_1       KFAQ---------KAQDVLATGL------ASKP--TLLELSKF-QGDSAAPSEP------
MGG_14967T0_5       EEAGSQREDSSANLWSYMGESVP------TCTRVRIPAGLHAY----GPFKNRN------
MGG_14967T0_1       NGNA---------ILEEKMPRLL------VTGE--GRNLAIQP-YHLASNAQAT------
MGG_03290T0_1       AHAG---------LIKPEIPL--------VVLD--EPNATPED----SAQPTGD------
MGG_14967T0_7       KDKQ---------LLSGLLGSET------IVVT--IQDIFGGT---AGGAAGSK------
MGG_02351T0_3       PAEE-----------SPFYTKVP------TMSV--SDLTPNEE-W-LHVPEPHT------
MGG_00022T0_1       S------------NWATLNAIVD------RCIVLDQEFVERIP-QTPEDSGSRK------
MGG_07858T0_1       KYEG---------LLSTHDVESV------IIDE-----------ALLSRLPSCG------
MGG_07858T0_4       NTKD---------RYAPFNKLK--------VVV--LPPLNVAE-WGPLNTSPLP------
MGG_07858T0_6       AQVS---------LWRSSGLSVQ------VVDN-----------VSIAALPDAG------
MGG_07858T0_2       RNEQ---------ALKTYKGLHS------IVVD----RNSIDC----LPSEAFR------
MGG_02351T0_7       ANQD---------LTSRLVQP--------TTKT--MPLGPDSYATLRGTTRTSDLPLQRC
MGG_02351T0_1       KYRG---------RAAGLAGGVP-------VVQ--LDD---SF-L-EAGAGDAV------
MGG_02351T0_9       STEE---------LASRLSDDAV------VLSV--DAHKIKQL---PESTVDGD------
MGG_12175T0_3       SSIR---------NLRSIQTGCQ------FLDI--SKEEDLIR-------YPDS------
MGG_00022T0_4       ELAS---------GVVPLGRPVS----------------NDGL-----------------
MGG_00022T0_3       TAEY---------GGRSLVLLGS------KVSLPKGLDDLPDT-EIVAIEDALKSAHEKG
MGG_00022T0_6       AQVP---------QSSELKAIAN------VELVRIGDAVESGE----HEAGDQN------
MGG_03810T0_1       ETAA---------LVARLGRDPN------DGVV--DISTLHHF-PLLGAAALPD------
MGG_08257T0_1       --------------------------------------------------ETQQ------
MGG_14897T0_1       RTKD---------LAAWLLKTCNQQDCIAVDVAELISSATNTY-DSISLEPTKP------
MGG_09589T0_1       QTAE---------VASWLSSKSS------DSKL--ELVD-----TSLATSAPRA------
MGG_12175T0_5       -------------MDRASNLDID------VSVP--VVGLDDDF-ILSSPSTPLT------
MGG_12447T0_1       TTKP---------LFDSLATNA-------VQIDVSMVQSSKTL----EASPKVA------
MGG_14943T0_1       A------------FVTTASTLEK------PLLN--VSSIPRAN-KPPGPRTTLS------
MGG_15097T0_1       RLES---------QTKNLGDAMA------TARFVNIENLAPAT-----NQRRSP------
MGG_15248T0_1       EQLD---------EWRPRHVRLA------FSVE-----SVPGC--AQADASTTT------
MGG_12175T0_1       TLAN---------VFSEEQHDVK------VIKL--GSDWADSC-WDNGCDLSDS------
MGG_14967T0_3       HGFE---------MLSSLDAVIE------AINV--DRIMALGI-HPPTARPKTA------
MGG_15681T0_1       ----------------------------------------EGF--VDLARPELG------
                                                                                

MGG_15682T0_1       -QEKYLPDPFA-------NDGT------------HVYNTGDLGKWNE-DGSIDILG----
MGG_14967T0_8       -DAVFRPDPWN-------AGNE------------LIYNTGDIGAYNA-EGELLYFS----
MGG_02611T0_2       LMNWFVDNNKWVEADRVHPTKDAAWRKYYKGPLDRLYRTGDLGKYLD-SGDVECTG----
MGG_14967T0_4       -FIELRDFPGL-----------------------KFYRTGDLARWLP-DMRIQILG----
MGG_05025T0_2       -DKKFVRDVFQ-------KGD-------------TYYRTGDALRRDN-DGRWYFMD----
MGG_09647T0_2       -GGLEVVEHGA----------GV-----------RWYRTGDIGRQDE-DGFVYIVG----
MGG_15248T0_2       -GAVFRPDQVM-------DNGE------------MSYDTGDMGYWDE-HGDLVCVG----
MGG_14967T0_2       -FLDAVLFPGM-------QRVSG-----------PWYCTGDYGYVEPSSGNVHLVG----
MGG_06199T0_2       -ASAFTKG--------------------------GFFRTGDQGKIDPEDGYVTITG----
MGG_08288T0_3       -GEVMVRDENG-------V---------------LWLKTGDEAVFDA-DGYCSITG----
MGG_12175T0_6       -AERFPTLEYF----------GE-----------RVYRTGDLVRILH-DGCFDFLG----
MGG_14967T0_6       -PCPFIQHIKY-------G---------------PLYLTGDLASFEP-DGTIVCKG----
MGG_12175T0_4       -REKFVEHPEY-------G---------------RLYRSGDLGRMLP-DGSLVISG----
MGG_07858T0_3       -REAFVRGLVW-------AKDPAR----------RFYRTGDLGVLND-DGSLSFIS----
MGG_07803T0_2       -ASKFHNITLA-------DGHPS-----------RLYRTGDKGFIDD-DGKLHIQG----
MGG_02351T0_6       -RQRFHETPRF-------LAAGHGEVPGRQG---RIYYSGDLGRYDS-AGNLVYMG----
MGG_00022T0_2       -SRFLQEAPKW-------RRERGAPYEAEPF---RMFRTGDLGRYKS-DGSIVYLG----
MGG_12175T0_2       -ASAFIDSKTY-------G---------------RLYRTGDKARLRA-DGLLECLG----
MGG_02351T0_10      -AAAYVETPAW-------LSHGAEGHAPRRG---TVYMTGDLARYGA-DGSLDFIG----
MGG_07858T0_5       -REVFVPAPAW-------LRDFGYSTDQ------VLYKTGDLVRQDLTDGSLLYLG----
MGG_07858T0_7       -AEAFINDPAW-------SLKLDGKHR-------RLYKSGDLAYYDA-DGCIIFCG----
MGG_14767T0_1       -AEVFVRDPIW-------LRQGHTGSKGRRG---LLYKTGDLVKYDA-NGYIVFVG----
MGG_02351T0_4       ------REA-------------------------RLYQTGDLVRYDG-CGRVVFIG----
MGG_02351T0_2       -ASAFVHDPPW-------LLAGSSTHPGRRG---RLYKTGDLFRYDA-QGNLLFVG----
MGG_02351T0_8       -AAAFIDSPGW-------LVRGSPDGSVPGRSGARLYKTGDLVRYNADDGSLVFLG----
MGG_00689T0_1       -RAIRKADPDN-------KLVEKYGRHGGLKSLRALFLAGERSEPAIVEAYQEVLN----
MGG_09647T0_1       NASTATRLPNT-------T--AA-----------IVYTSGTSGRP---KGVKITAH----
MGG_04646T0_1       -ITLDGGSPGN-------A--GM-----------MLYTSGTTNRP---KGVLLPQD----
MGG_14967T0_5       -MLFPVQDRSD-------NDIAY-----------VLYTSGSTGVP---KGVPIKHG----
MGG_14967T0_1       ---CVDPSEDD-------V--AA-----------VLFTSGSTGNA---KGVQLTHR----
MGG_03290T0_1       -ANQELPADDD-------LDRLAF----------VCYTSGTTGRP---KGIANPHR----
MGG_14967T0_7       -GRLESTRPKL-------DEVAA-----------ILFTSGSTGLP---KGVLMPHR----
MGG_02351T0_3       ------VTPSD-------P--AL-----------VLFTSGSTGTP---KSILWSHE----
MGG_00022T0_1       -LKQQTRKPQP-------SDLAY-----------VIFSSGSTGEP---KGSMVAHW----
MGG_07858T0_1       -SVEDISQPAD-------I--SY-----------IIFTSGTTGRS---KGIVSNHS----
MGG_07858T0_4       -SPLNKVKPSN-------L--AY-----------VLFTSGSTGRP---KGVMTEHR----
MGG_07858T0_6       -PELPITNATM-------SSSLY-----------VIFTSGSTGVP---KGCLIEHR----
MGG_07858T0_2       -SDVKPTNAAW-----------------------VVYSSGSTGTP---KGAVLEHR----
MGG_02351T0_7       LDKLPRVAPSD---------LLY-----------AVFTSGSTGTP---KGCQIEHG----
MGG_02351T0_1       -AKLPAVSASD-------T--VY-----------ISFTSGTTGQP---KGACISHA----
MGG_02351T0_9       -PSLPKTSPTD-------V--LY-----------IVFTSGSTGVP---KGIVTTHQ----
MGG_12175T0_3       -NPDITPDASR-------V--AN-----------IIYTSGSTGIP---KGVCVTQL----
MGG_00022T0_4       ----------------------------------VVMDSQQNPVPAGVMGELVVFGDGLS
MGG_00022T0_3       LTATDSGNPTA-------TSLAA-----------IIFTSGSTGKP---KGSMLEHR----
MGG_00022T0_6       -LNLDMAGPSA-------TSLAY-----------TIFTSGSTGKP---KGVMLEHR----
MGG_03810T0_1       -VSGLDIESSD-------E--AM-----------LLYTSGTTGEP---KGISIPHR----
MGG_08257T0_1       -HAMAI----------------------------LIYTSGTTGLP---KAAVVSWA----
MGG_14897T0_1       -TKPSTPTTTT-------TTTKATTPTPTELPGIILYTSGSTGTP---KGVLVTQR----
MGG_09589T0_1       -RIVNRSTPDA-------P--AM-----------IIYTSGTTGTP---KGAILTQG----
MGG_12175T0_5       -DRQAELSPQD-------R--SY-----------CLYTSGTTGTP---KGCEITHE----
MGG_12447T0_1       -IHAKAPSAAA-----------------------VFYTSGSTGVP---KGITLSHA----
MGG_14943T0_1       -FPETTRRPTD-------P--AA-----------VLYTSGSTGTP---KGIVLSHE----
MGG_15097T0_1       -IATEADHVAA-----------------------LMYTSGSTGVP---KAIVIKHE----
MGG_15248T0_1       -PVPRTPRPHW---------PAY-----------ICFTSGSTGVP---KPVVCTHA----
MGG_12175T0_1       -ISHRAATPSD-------L--AY-----------VMYTSGSTGTP---KGVGVSHA----
MGG_14967T0_3       -LPPII-SPDS-------T--CY-----------VMLTSGSTGTP---KPAILTHR----
MGG_15681T0_1       ---------------------CY-----------VIYTSGTTGEP---KGVDVMHS----
                                                          :                     

MGG_15682T0_1       -RVD-DQIKIKGFRV--ELDG-----------------------VSASLS----SGPGIT
MGG_14967T0_8       -RND-RQVKIHGQRT--ELGE---------IESLLGSNDEQVVVILFNNGQGNNNSPRLI
MGG_02611T0_2       -RAD-DQVKIRGFRI--ELND-ID----SNLSQSSLIRDCKTLVRRDKN-----EEPKLV
MGG_14967T0_4       -RRD-AQLKVAGMRI-------HPAEIETVLESHPDVLRASVAS----------CSGRLC
MGG_05025T0_2       -RLG-DTFRWKGENV-------STAEVGEVLGNFPGVVEANVYGVQLPNHDG--RAGAAA
MGG_09647T0_2       -RRK-D------------------------------------------------------
MGG_15248T0_2       -RRD-RQVKLRGYRV--ELND-LEIRIAETVPEANAVAVAVRKGLVDELLVMVQPGGLDI
MGG_14967T0_2       -RMD-DQVKVNGQRV--ELGDIEAVVSQYVGRCTVLAHSVGGRRRLFAVV----SRKRDL
MGG_06199T0_2       -RIK-ELINKAGEKI--SPIE-LDNVLTRHEAVSEAVSFAVPSELYGQ------DVGVAV
MGG_08288T0_3       -RFK-D------------------------------------------------------
MGG_12175T0_6       -RAD-DQVKLRGQRL--EIGE-INH---AIKTGISQVQDVATLVIRDESK----QKDFLV
MGG_14967T0_6       -RMD-NMINLRGLRV--ELGA-VE--------------SVAEEVLVGRTG----------
MGG_12175T0_4       -RVD-DQIKLRGQRI--ELKE-IDS---VTRESESVNAAVTILVSRGTQK----ADQLAT
MGG_07858T0_3       -RKD-TQIKLNGQRV--ELGE-IEAVLLKTSNLAQVCVEAFSPQSSP-------RRKLLA
MGG_07803T0_2       -RIGNREIKVRGYRL--DLYE---------------------------------VEKNVM
MGG_02351T0_6       -RKD-AQLKIRGQLV--APEE-VEAQIRTWLNDNNNNNNNNISNSNSNNN----SKPEVV
MGG_00022T0_2       -RSD-LQVKIRGQRV--EMGD-VET---NLRRFLPSDTPIPIVEAIPRPD----GRMTLV
MGG_12175T0_2       -RISDGQVKLRGQRM--ELGE-VEAAILRVQGCHGAVAAVV-------------NGSILV
MGG_02351T0_10      -RKD-ALVKLRGQRV--ELAE-VEYHVAACLREGGPCVGIAAEIVTPKNG----SSPILT
MGG_07858T0_5       -RKD-NQTKINGQRL--EIGE-------IEAVLNGKDAAIEQVVVVAGKTTIDKNKQVLV
MGG_07858T0_7       -RKD-AQVKVRGQRM--ELGE--------IESHLSQNPEIQHAAVFYPASGP--CKGQLV
MGG_14767T0_1       -RKD-QQVKLRGQRI--ELSE-IEY---HLRKNLPPCVKIAAEVVRPSG-----AEPTLV
MGG_02351T0_4       -RKHESQRKLRGQRV--ELGE-IEL---RVHEFLAGRLEATVVAEIFCPDKS--DKETLA
MGG_02351T0_2       -RKDTSQLKIRGQRV--EIGD--------------VEHDVLSLD----------------
MGG_02351T0_8       -RKD-AQVKLRGQRI--ELGE-VEHHLRQCLAAEFAEPSVAAEVVVPAAT----GSATLA
MGG_00689T0_1       -KYAAPNAHVIDNWWSTESGS-PISGIALVPQHGKDGKTCVRTQKTKPLSSKPGSAGKPM
MGG_09647T0_1       -NLL-ATAINYAVL---GEVE-PTS---VLLC------DVPLFHLM--------------
MGG_04646T0_1       -VMT-AQARSLLQA----------------------------------------------
MGG_14967T0_5       -GLK-NSVAEHRRC---CMFS-TAT---RLLGVAPWTFDVSVVDMFGPLS----IGAQLV
MGG_14967T0_1       -NLI-LPARFLAERE--KIGP-SS----RVFQFARSSFDVHLIDIMCALL----HGGLLL
MGG_03290T0_1       -APV-RSYSLRFELS--DLKP-GDR------VACNVFF---IWEILRPLL----RGATVV
MGG_14967T0_7       -QAA-GFGVMMASAL--QYRT-SD----RVFAFARMLFDVALTDIFGTFY----AGATLL
MGG_02351T0_3       -TLS-SNICAARDSF--G-IT-AQS---RVLQFAGYEFDVSTVESLAVLS----AGGTLC
MGG_00022T0_1       -SFT-SSASELFPAL--G-LD-HTT---RTIQFASYAFATSLVETFATLG----HGGCVC
MGG_07858T0_1       -SFC-TSILAHGKAEFYGPES-------RCFAFSAYNFDVSVTDIFTTLA----FGACIC
MGG_07858T0_4       -SVC-ASTAGHGAAM--GFGD-FPR---RVLQFATYTFDACIGEIFTTLS----HGGTIC
MGG_07858T0_6       -AFL-YSCQAQARIF--GMRP-DH----RVLQGCPYSFDVSVMEILTTLL----HGACVC
MGG_07858T0_2       -SLA-T------------------------------------------------------
MGG_02351T0_7       -SFC-SAVVYQERVI--APLR-PGA---RVYDLSSYSFDASIWMILRSLA----AGATLC
MGG_02351T0_1       -NVR-SAVHYQGRDL--GFSR-ES----RVFDFAPYSFDVAWSNFLHTLC----AGGCLC
MGG_02351T0_9       -NFA-SAAAHQADML--HIRR-GT----RVFDFVSYNFDVSWSNHLQTLI----SGGCLC
MGG_12175T0_3       -NIM-SNLDVLSRLY--PLSE-GTDKPGRLLQSCSQAFDVSVFEIFYAWK----MGMCLC
MGG_00022T0_4       RGYT-NSALDKNRFIHIDLESRGLTRAYRSGDRVRVSPKARQIEFFGRMDMQVKIRGHRV
MGG_00022T0_3       -SIV-RLVKDSNVVA--KVPP-AAA----VAHVANISFDVSMWEMYTPLL----NGGTVV
MGG_00022T0_6       -AIL-RIALDSNLC---DYFP-ESP---VVSNVCNLGFDVSVQEIWTALL----RGGTLV
MGG_03810T0_1       -IVV-NGIEGMIQRWP-ELKS-KPL---TVLQHCSLGFDVSWFTVLLGLA----CKGQAV
MGG_08257T0_1       -KMI-VAGGFTSRLL--NLQT---------------------------------------
MGG_14897T0_1       -SVI-SIATAINTVA--DHQT-PP----VVLQQSSIGFDVSLMQIFSALF----TGGSLV
MGG_09589T0_1       -NYV-AISGSIARAL--ALRH-GSE---SVLQQSSPGFDMSQVQIFPCLA----TGSRLV
MGG_12175T0_5       -NAVQAMLAFQDLFS--GHWD-QDS---KWLQFASFHFDVSVLEQYWSWS----VGIALV
MGG_12447T0_1       -SLT-YNIMAATRQF--GFKE-GVD---IMLQQSSFSFDMALAQMLTSLS----NGGTLV
MGG_14943T0_1       -NLV-HEIEFSS--A--SYDF-GVE---RVLCQSALGFDMSLTQIFSALA----FGGSLH
MGG_15097T0_1       -SMR-NSIEAFTKVV--GYRE-GHE---VSLHQSSYSFDMSLSQIFLDLA----NGGTVH
MGG_15248T0_1       -GLV-AFQRDPTVRL--GAKP-GVR---VSQI-MSVAFDGSIHEIFSALT----YGATLV
MGG_12175T0_1       -AAT-QSLLAHDEHI--PHFR-------RFLQFAAPTFDVSVFEIFFPLF----RGVTLV
MGG_14967T0_3       -AVT-SAVQQAVKAY--ALGP-SSR---VLLC-ANYIFDASATDIYGSLI----TGATLV
MGG_15681T0_1       -NVT-NLLCLGPGNL--GIKP-GMC----VGQVLNISFDMAAWEILGCLC----NGGTLV
                                                                                

MGG_15682T0_1       GAVA--------------------------------------------------------
MGG_14967T0_8       GFHAANS-----------------------------------------------------
MGG_02611T0_2       SYVV--------------------------------------------------------
MGG_14967T0_4       AMVQAKDCASPSLEGRD-------------------------------------------
MGG_05025T0_2       IYIEPEKKASFDTAA---------------------------------------------
MGG_09647T0_2       ------------------------------------------------------------
MGG_15248T0_2       AA----------------------------------------------------------
MGG_14967T0_2       SPPEEDVRRDFDGAALEKV-----------------------------------------
MGG_06199T0_2       VLKPGAKLGKDE------------------------------------------------
MGG_08288T0_3       ------------------------------------------------------------
MGG_12175T0_6       SFVVADDQSDSSEAQSQTLEPIFSPDAATLARD---------------------------
MGG_14967T0_6       ------------------------------------------------------------
MGG_12175T0_4       FYVPLATAETEKHAVSYQVLDDAQTARPAPESQA--------------------------
MGG_07858T0_3       AFIQLERRPSNEKAEASSALEFVDMTSSTREKLVS-------------------------
MGG_07803T0_2       ------------------------------------------------------------
MGG_02351T0_6       VDVVSRAGSKHTLVAYITAETAELELMTSA------------------------------
MGG_00022T0_2       AFLTGPLGKGDKERTEETYVIADSAARQS-------------------------------
MGG_12175T0_2       AFCLLDSLHGEDHTSAEPR-----------------------------------------
MGG_02351T0_10      VFLSVGDSETPKETEPQETEAKLVQILQ--------------------------------
MGG_07858T0_5       AFVEFVSKSSNNDMLLELDDESRLKMKE--------------------------------
MGG_07858T0_7       GLVSLKKVGAETNRDGIVELVDGQETSIAAAITSD-------------------------
MGG_14767T0_1       VFVDEQQPVVNGTKTKTKKVKNDKVGLDDVVKLSPEL-----------------------
MGG_02351T0_4       LFVSPLSLPDDADNVTDHLKRALPVDE---------------------------------
MGG_02351T0_2       ------------------------------------------------------------
MGG_02351T0_8       AFVQIPAGERPRFQEAIRG-----------------------------------------
MGG_00689T0_1       PGFDVRVVNDEGEELPRGKMGNIVMAAPLAPT----------------------------
MGG_09647T0_1       ------------------------------------------------------------
MGG_04646T0_1       ------------------------------------------------------------
MGG_14967T0_5       LGRR--------------------------------------------------------
MGG_14967T0_1       QVSQDK------------------------------------------------------
MGG_03290T0_1       A-VPDNVSYDPVALVDLLASRKITETLMTPTLLATVL-----------------------
MGG_14967T0_7       LAPHAEC-----------------------------------------------------
MGG_02351T0_3       IPSEADRTNR--------------------------------------------------
MGG_00022T0_1       IPSADERINDTA------------------------------------------------
MGG_07858T0_1       IPSDEEKMNALAATAARMRVTHITATPTVSQFINPGD-----------------------
MGG_07858T0_4       VPTEQERMD---------------------------------------------------
MGG_07858T0_6       VP----------------------------------------------------------
MGG_07858T0_2       ------------------------------------------------------------
MGG_02351T0_7       VPSEQERRDDLE------------------------------------------------
MGG_02351T0_1       VASEDDMLADLSAA----------------------------------------------
MGG_02351T0_9       IPSESDRRNDIAGA----------------------------------------------
MGG_12175T0_3       SA----------------------------------------------------------
MGG_00022T0_4       EPAEVEQVMLALPVVRDAVVVVRQ------------------------------------
MGG_00022T0_3       CIDYLTTLDIPAL-----------------------------------------------
MGG_00022T0_6       C-VDHFTLLDSRQLEEVFMKNKVSVAILTPALIRQCL-----------------------
MGG_03810T0_1       I-ASRDVRGDPRALARIIVQNGINCTVATPSETMAWL------------QGDHLGELASS
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       V-CPHEHRRDPIETARLMRRFAVTTVFATPTEWTLLL------------GPDGQGLARCS
MGG_09589T0_1       I-ASRAQRADPAALALLMEREKVTVMTGTQTEVMQILQARDDPRDAGCDDGEEQIIKRCR
MGG_12175T0_5       AAP---------------------------------------------------------
MGG_12447T0_1       V-VPSHLRGDALGLSQLIVAENVSIVQASPTEYKSLI------------GVNA-QHLKTS
MGG_14943T0_1       M-LPRSQRGDALAITKRILDSGITLTGATPSEYMSWI------------SFGG-ADLARS
MGG_15097T0_1       V-VPRELRGDPEAIASIIAREGITFTSATPSEVISWI------------EHGSLSELGSS
MGG_15248T0_1       LPA---------------------------------------------------------
MGG_12175T0_1       SCDRRLMLD---------------------------------------------------
MGG_14967T0_3       LRSDNELRTDLAATVLA-------------------------------------------
MGG_15681T0_1       L-----------------------------------------------------------
                                                                                

MGG_15682T0_1       ------------------------------------------------------------
MGG_14967T0_8       ------------------------------------------------------------
MGG_02611T0_2       ------------------------------------------------------------
MGG_14967T0_4       ------------------------------------------------------------
MGG_05025T0_2       ------------------------------------------------------------
MGG_09647T0_2       ------------------------------------------------------------
MGG_15248T0_2       ------------------------------------------------------------
MGG_14967T0_2       ------------------------------------------------------------
MGG_06199T0_2       ------------------------------------------------------------
MGG_08288T0_3       ------------------------------------------------------------
MGG_12175T0_6       ------------------------------------------------------------
MGG_14967T0_6       ------------------------------------------------------------
MGG_12175T0_4       ------------------------------------------------------------
MGG_07858T0_3       ------------------------------------------------------------
MGG_07803T0_2       ------------------------------------------------------------
MGG_02351T0_6       ------------------------------------------------------------
MGG_00022T0_2       ------------------------------------------------------------
MGG_12175T0_2       ------------------------------------------------------------
MGG_02351T0_10      ------------------------------------------------------------
MGG_07858T0_5       ------------------------------------------------------------
MGG_07858T0_7       ------------------------------------------------------------
MGG_14767T0_1       ------------------------------------------------------------
MGG_02351T0_4       ------------------------------------------------------------
MGG_02351T0_2       ------------------------------------------------------------
MGG_02351T0_8       ------------------------------------------------------------
MGG_00689T0_1       ------------------------------------------------------------
MGG_09647T0_1       ------------------------------------------------------------
MGG_04646T0_1       ------------------------------------------------------------
MGG_14967T0_5       ------------------------------------------------------------
MGG_14967T0_1       ------------------------------------------------------------
MGG_03290T0_1       -SRHSKLGDRLPDLRTLWLNGEVVMADLARRTLSALPNTRLLNCYSASETHEIACGDIRE
MGG_14967T0_7       ------------------------------------------------------------
MGG_02351T0_3       ------------------------------------------------------------
MGG_00022T0_1       ------------------------------------------------------------
MGG_07858T0_1       --------------VPTVKTFITGGEFASPEIIKKWVSAGRNYINIYGPAECNSRITHHS
MGG_07858T0_4       ------------------------------------------------------------
MGG_07858T0_6       ------------------------------------------------------------
MGG_07858T0_2       ------------------------------------------------------------
MGG_02351T0_7       ------------------------------------------------------------
MGG_02351T0_1       ------------------------------------------------------------
MGG_02351T0_9       ------------------------------------------------------------
MGG_12175T0_3       ------------------------------------------------------------
MGG_00022T0_4       ------------------------------------------------------------
MGG_00022T0_3       ------------------------------------------------------------
MGG_00022T0_6       -----THAPDIIRRLAVLISVADKMDPGDAMKASKLVSRAVLNGYGPTENGMLSTIYEVD
MGG_03810T0_1       DWGWHVAVGEPIPAAFLRQVHQHGK-----PSLRVINAYGPSETWMPLSHEIPLGQARTM
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       SLRKAMAAGEMVTGGLAARFRRLEKARGGDSRLELFNVYGPTETCMSSNVGR-IEYWLDE
MGG_09589T0_1       HLQTVGVGGEPFSAQLAAQFVLLENATG--RRLDVFNMYGPTETCMISNIGR-IEYW-GN
MGG_12175T0_5       ------------------------------------------------------------
MGG_12447T0_1       KWRVALSGGENMTQSLLEVFRSLGK-----PDLVLFNGYGPTEATINANTRI-VPYH---
MGG_14943T0_1       NWRRAVCGGEPVTTSLLRAFDSIGR-----PELRLFNAYGPTETTCSATRTE-LDYR---
MGG_15097T0_1       SWRKVVCGGEPVKESLINGLRKIDK-----PDLAFFDGYGPTEITFCCAMRA-VDYR---
MGG_15248T0_1       ------------------------------------------------------------
MGG_12175T0_1       ------------------------------------------------------------
MGG_14967T0_3       ------------------------------------------------------------
MGG_15681T0_1       ------------------------------------------------------------
                                                                                

MGG_15682T0_1       ------------------------------------------------------------
MGG_14967T0_8       ------------------------------------------------------------
MGG_02611T0_2       ------------------------------------------------------------
MGG_14967T0_4       ------------------------------------------------------------
MGG_05025T0_2       ------------------------------------------------------------
MGG_09647T0_2       ------------------------------------------------------------
MGG_15248T0_2       ------------------------------------------------------------
MGG_14967T0_2       ------------------------------------------------------------
MGG_06199T0_2       ------------------------------------------------------------
MGG_08288T0_3       ------------------------------------------------------------
MGG_12175T0_6       ------------------------------------------------------------
MGG_14967T0_6       ------------------------------------------------------------
MGG_12175T0_4       ------------------------------------------------------------
MGG_07858T0_3       ------------------------------------------------------------
MGG_07803T0_2       ------------------------------------------------------------
MGG_02351T0_6       ------------------------------------------------------------
MGG_00022T0_2       ------------------------------------------------------------
MGG_12175T0_2       ------------------------------------------------------------
MGG_02351T0_10      ------------------------------------------------------------
MGG_07858T0_5       ------------------------------------------------------------
MGG_07858T0_7       ------------------------------------------------------------
MGG_14767T0_1       ------------------------------------------------------------
MGG_02351T0_4       ------------------------------------------------------------
MGG_02351T0_2       ------------------------------------------------------------
MGG_02351T0_8       ------------------------------------------------------------
MGG_00689T0_1       ------------------------------------------------------------
MGG_09647T0_1       ------------------------------------------------------------
MGG_04646T0_1       ------------------------------------------------------------
MGG_14967T0_5       ------------------------------------------------------------
MGG_14967T0_1       ------------------------------------------------------------
MGG_03290T0_1       MLTEDASVCPVGPPLDPKHTYILDENFQKVEPGSSGELFLGGHLLARGYLNLPETTAK--
MGG_14967T0_7       ------------------------------------------------------------
MGG_02351T0_3       ------------------------------------------------------------
MGG_00022T0_1       ------------------------------------------------------------
MGG_07858T0_1       FKVGDSGSCIGRPSGCVVWITKSNDPNALVPLGAPGELLIEGHLVSNGYLKEEDKTAEAF
MGG_07858T0_4       ------------------------------------------------------------
MGG_07858T0_6       ------------------------------------------------------------
MGG_07858T0_2       ------------------------------------------------------------
MGG_02351T0_7       ------------------------------------------------------------
MGG_02351T0_1       ------------------------------------------------------------
MGG_02351T0_9       ------------------------------------------------------------
MGG_12175T0_3       ------------------------------------------------------------
MGG_00022T0_4       ------------------------------------------------------------
MGG_00022T0_3       ------------------------------------------------------------
MGG_00022T0_6       KTTVYPAGIPIGHAITNSGAVVMDSQQRIVSPGVIGELVVTGDGLARGYADP--------
MGG_03810T0_1       EDVERLWPVPIGSTMPNYAVRVEDVNGHVLPPGMPGQVVIGGCGVALGYVSSEPTVTDPR
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       NVQEPARVFAVGPPLDGVRIRVLGLDGNEVPYGAEGEVYIGGVGVGPGYLNR-PDLTDAA
MGG_09589T0_1       HRDEESRSWPVGPPFANARVYILDQAGRTVPSGSSGEIYIAGEGVGLGYLGR-ADLTRAS
MGG_12175T0_5       ------------------------------------------------------------
MGG_12447T0_1       EP-NSNPDLPL-LTWPNYSISIVDLELNPVPVGVFGEVCIGGAGVGLGYFKN-DELTAKA
MGG_14943T0_1       GPWGDRPTTSG-RAAPNCSVCIVDANLAPLPVGMPGEVLIGGAKVALGYLGS-CELTATR
MGG_15097T0_1       SDAPPDAEAGGFKPWPNVSVYILDADQKIVPAGVTGEIAIGGGGVVAGY-GD-HKLSAAA
MGG_15248T0_1       ------------------------------------------------------------
MGG_12175T0_1       ------------------------------------------------------------
MGG_14967T0_3       ------------------------------------------------------------
MGG_15681T0_1       ------------------------------------------------------------
                                                                                

MGG_15682T0_1       ------------------------------------------------------------
MGG_14967T0_8       ------------------------------------------------------------
MGG_02611T0_2       ------------------------------------------------------------
MGG_14967T0_4       ------------------------------------------------------------
MGG_05025T0_2       ------------------------------------------------------------
MGG_09647T0_2       ------------------------------------------------------------
MGG_15248T0_2       ------------------------------------------------------------
MGG_14967T0_2       ------------------------------------------------------------
MGG_06199T0_2       ------------------------------------------------------------
MGG_08288T0_3       ------------------------------------------------------------
MGG_12175T0_6       ------------------------------------------------------------
MGG_14967T0_6       ------------------------------------------------------------
MGG_12175T0_4       ------------------------------------------------------------
MGG_07858T0_3       ------------------------------------------------------------
MGG_07803T0_2       ------------------------------------------------------------
MGG_02351T0_6       ------------------------------------------------------------
MGG_00022T0_2       ------------------------------------------------------------
MGG_12175T0_2       ------------------------------------------------------------
MGG_02351T0_10      ------------------------------------------------------------
MGG_07858T0_5       ------------------------------------------------------------
MGG_07858T0_7       ------------------------------------------------------------
MGG_14767T0_1       ------------------------------------------------------------
MGG_02351T0_4       ------------------------------------------------------------
MGG_02351T0_2       ------------------------------------------------------------
MGG_02351T0_8       ------------------------------------------------------------
MGG_00689T0_1       ------------------------------------------------------------
MGG_09647T0_1       ------------------------------------------------------------
MGG_04646T0_1       ------------------------------------------------------------
MGG_14967T0_5       ------------------------------------------------------------
MGG_14967T0_1       ------------------------------------------------------------
MGG_03290T0_1       ------SFLPDAFDLAPGARMYRTGDLARILP-SGLLEITGRV--GGMIKVRGYSVQPGA
MGG_14967T0_7       ------------------------------------------------------------
MGG_02351T0_3       ------------------------------------------------------------
MGG_00022T0_1       ------------------------------------------------------------
MGG_07858T0_1       IAAP--DWLVRMFPDRASSRLYRTGDLAQWLPNGKLRLLGRRDTQMKIHGVRLEAAHIEF
MGG_07858T0_4       ------------------------------------------------------------
MGG_07858T0_6       ------------------------------------------------------------
MGG_07858T0_2       ------------------------------------------------------------
MGG_02351T0_7       ------------------------------------------------------------
MGG_02351T0_1       ------------------------------------------------------------
MGG_02351T0_9       ------------------------------------------------------------
MGG_12175T0_3       ------------------------------------------------------------
MGG_00022T0_4       ------------------------------------------------------------
MGG_00022T0_3       ------------------------------------------------------------
MGG_00022T0_6       -VLNRDRFVDVTIKGR-LVRAYRTGDRVRWRPDDYEIDYFGRE--GQLLKIRGHLVEPAE
MGG_03810T0_1       FLPD--SHPAEVHLARGWDKVHPSGDYGYMTE-EGLFFSLGRISGDTQIKLRGMRLDLRH
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       FLPEPTNDPPAAAGSGRSKKMYRTRDKGYWLP-DGSLMVCGRIDGDTQVKMHGIRIELED
MGG_09589T0_1       FVAD-------TFGPGNT-KMYRTGDSGFLDP-DGSLVILGRIQDDSQVKIRGIRIELDE
MGG_12175T0_5       ------------------------------------------------------------
MGG_12447T0_1       FVAD--KTAPAEFVAKGWKTKFRTGDLGRLSP-DGGLIIEGRIDGDTQVKLRGMRIDLKN
MGG_14943T0_1       FIPH--ASIHEDFAARGWTSVHRTGDVGRLLP-DGALVLQGRVDGDTRVKLRGNRVDLVD
MGG_15097T0_1       FKHD--KWASSEFVQSGWTRLHLTGDVGKIDPIDGTLKLKGRIAGDTQIKLRGMRLDVRE
MGG_15248T0_1       ------------------------------------------------------------
MGG_12175T0_1       ------------------------------------------------------------
MGG_14967T0_3       ------------------------------------------------------------
MGG_15681T0_1       ------------------------------------------------------------
                                                                                

MGG_15682T0_1       ------------------------------------------------------------
MGG_14967T0_8       ------------------------------------------------------------
MGG_02611T0_2       ------------------------------------------------------------
MGG_14967T0_4       ------------------------------------------------------------
MGG_05025T0_2       ------------------------------------------------------------
MGG_09647T0_2       ------------------------------------------------------------
MGG_15248T0_2       ------------------------------------------------------------
MGG_14967T0_2       ------------------------------------------------------------
MGG_06199T0_2       ------------------------------------------------------------
MGG_08288T0_3       ------------------------------------------------------------
MGG_12175T0_6       ------------------------------------------------------------
MGG_14967T0_6       ------------------------------------------------------------
MGG_12175T0_4       ------------------------------------------------------------
MGG_07858T0_3       ------------------------------------------------------------
MGG_07803T0_2       ------------------------------------------------------------
MGG_02351T0_6       ------------------------------------------------------------
MGG_00022T0_2       ------------------------------------------------------------
MGG_12175T0_2       ------------------------------------------------------------
MGG_02351T0_10      ------------------------------------------------------------
MGG_07858T0_5       ------------------------------------------------------------
MGG_07858T0_7       ------------------------------------------------------------
MGG_14767T0_1       ------------------------------------------------------------
MGG_02351T0_4       ------------------------------------------------------------
MGG_02351T0_2       ------------------------------------------------------------
MGG_02351T0_8       ------------------------------------------------------------
MGG_00689T0_1       ------------------------------------------------------------
MGG_09647T0_1       ------------------------------------------------------------
MGG_04646T0_1       ------------------------------------------------------------
MGG_14967T0_5       ------------------------------------------------------------
MGG_14967T0_1       ------------------------------------------------------------
MGG_03290T0_1       VESVVMKHLAVRHCAVVSHGEGLKRQLVSYFVRDKENPGDRVDPIV---------QE---
MGG_14967T0_7       ------------------------------------------------------------
MGG_02351T0_3       ------------------------------------------------------------
MGG_00022T0_1       ------------------------------------------------------------
MGG_07858T0_1       KLSAALPSGSQAVVEKITVGQDPKGGQESKGGQESKREKLAAFVTLPGPPTNDDTPSFLE
MGG_07858T0_4       ------------------------------------------------------------
MGG_07858T0_6       ------------------------------------------------------------
MGG_07858T0_2       ------------------------------------------------------------
MGG_02351T0_7       ------------------------------------------------------------
MGG_02351T0_1       ------------------------------------------------------------
MGG_02351T0_9       ------------------------------------------------------------
MGG_12175T0_3       ------------------------------------------------------------
MGG_00022T0_4       ------------------------------------------------------------
MGG_00022T0_3       ------------------------------------------------------------
MGG_00022T0_6       VEAALLAAHEAVESAAVVG--------LSKPGSDTDLVGFIRLHGSDNRAAAAAAAA---
MGG_03810T0_1       VEAAMMDMEMAQGFVVDVVVGVRSTDGQPLAAGSLADDSTSKVLVAHAVTDASTATT---
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       VASAILAAADGL---------------VSHAVATVRSDEHDKTIVAFVVPSPRLSPA---
MGG_09589T0_1       VSSVIVRSSGGR---VSQA---------ITTVRGTGENKMMVSFAVLNEGSKEDRKD---
MGG_12175T0_5       ------------------------------------------------------------
MGG_12447T0_1       IESAILQAGAGK---IIDA-------AVSVRRGGADESEPQYLVGHVVLDADQTPED---
MGG_14943T0_1       VEEAMLQAGQGQ---LLQVFACLYCPDLASDDGALAHPESAVLAALVVVDPCHPSAD---
MGG_15097T0_1       VELAIMKTAQGQ---INDV--------VVTAHHNKATGASSLIAFAIVADP-KASHD---
MGG_15248T0_1       ------------------------------------------------------------
MGG_12175T0_1       ------------------------------------------------------------
MGG_14967T0_3       ------------------------------------------------------------
MGG_15681T0_1       ------------------------------------------------------------
                                                                                

MGG_15682T0_1       ------------------------------------------------------------
MGG_14967T0_8       ------------------------------------------------------------
MGG_02611T0_2       ------------------------------------------------------------
MGG_14967T0_4       -----------LAAFCRTILPGRLVPSFISSVDRLP-VLPSQKIDRAK------------
MGG_05025T0_2       -----------FLAHARKHLPKYAV-----------------------------------
MGG_09647T0_2       ------------------------------------------------------------
MGG_15248T0_2       -----------MRSRLEATFPRYLLPGHIVAVDAIP-TTPAGKIDY--------------
MGG_14967T0_2       -----------VFNACSKCLPPYMIPRTI-AVQAIP-QSPSGKIDA--------------
MGG_06199T0_2       -----------LREWVAARLAKFKVPEKIYYTEIMP-KTATGKIQR--------------
MGG_08288T0_3       ------------------------------------------------------------
MGG_12175T0_6       -----------VQDSCRAKLPGYMVPTYILKLPFMPLSSNNK------------------
MGG_14967T0_6       ------------------------------------------------------------
MGG_12175T0_4       -----------IFHLLTSRLPTYMIPNYLIPISVIP-TTPSGKVDKARL-----------
MGG_07858T0_3       -----------IKQNAANHLPEYMVPSLFIPVYSLP-INASGKIERKV------------
MGG_07803T0_2       ------------------------------------------------------------
MGG_02351T0_6       -----------LTTKLEATLPRYAVPSYYIPVPAIP-TNASGKKDRKR------------
MGG_00022T0_2       -----------ITSKLLKVLPQYCVPTHFIRLKELP-KTVTGKTSRK-------------
MGG_12175T0_2       -----------ITKACEDWLPKFMVPNEVLVLDEFP-RLPSGKVDRK-------------
MGG_02351T0_10      -----------DLEQLPDRVPQYMVPGAYISIPQIP-MTTTNKTDRRA------------
MGG_07858T0_5       -----------LETLARASLPKYMVPTLWIPVSKMPSLATSSKTDRKT------------
MGG_07858T0_7       -----------ATIQLSSLVPGYMIPNLWIPVKSFP-LLPSEKLNRKC------------
MGG_14767T0_1       -----GAIVADMDGLLGEELPRYMVPAAYIPLQSMP-VLASAKIDRKR------------
MGG_02351T0_4       -----------LEQALLESLPPHMIPKVYVPLAKMP-TNHSGKTDRR-------------
MGG_02351T0_2       ------------------------------------------------------------
MGG_02351T0_8       -----------LEDALKKRLPTYMVPSAYIPLEAIP-LAPSGKTDRKAL-----------
MGG_00689T0_1       -----------AFRTLWDDEPRFFRGYFKRFNGLWVDTGDTGVVDEDGYVHIMSRSDDII
MGG_09647T0_1       ------------------------------------------------------------
MGG_04646T0_1       ------------------------------------------------------------
MGG_14967T0_5       ------------------------------------------------------------
MGG_14967T0_1       ------------------------------------------------------------
MGG_03290T0_1       -----SGYSPVARKTLSAHLAHYMIPALWIELTELP-THEVSGKIDL-------------
MGG_14967T0_7       ------------------------------------------------------------
MGG_02351T0_3       ------------------------------------------------------------
MGG_00022T0_1       ------------------------------------------------------------
MGG_07858T0_1       PRQDLCDLLAGVQETMLANLPAWMCPNYILPLDKFP-HGQSGKVNRKV------------
MGG_07858T0_4       ------------------------------------------------------------
MGG_07858T0_6       ------------------------------------------------------------
MGG_07858T0_2       ------------------------------------------------------------
MGG_02351T0_7       ------------------------------------------------------------
MGG_02351T0_1       ------------------------------------------------------------
MGG_02351T0_9       ------------------------------------------------------------
MGG_12175T0_3       ------------------------------------------------------------
MGG_00022T0_4       -----------GEDEGEKELVAFVVADDK-------------------------------
MGG_00022T0_3       ------AQVFARERVSAALLSPVLVKQILQR-----------------------------
MGG_00022T0_6       -----SSIESQTLKALRMVLPTYMVPVRVVVLEEWP-LNASGKLDRKQ------------
MGG_03810T0_1       -----DTDERLRSIAENLPLPDYMRPAVVVPVDSIP-LTPNGKQDRAA------------
MGG_08257T0_1       ------------------------------------------------------------
MGG_14897T0_1       -----DAPKFLAELPARLPLAEYMRPAAILPLETLP-LNASGKLDMAAL-----------
MGG_09589T0_1       -----SDAAFLAALASSLPLPSYMCPAAILPLQKFP-TTASGKLDRASL-----------
MGG_12175T0_5       ------------------------------------------------------------
MGG_12447T0_1       -----SQQDFLAQLIPRLRLPRHMKPSLLVPIRALP-QTASHKLDRRAL-----------
MGG_14943T0_1       -----REELF-ADLLKRVSLPRAQKPTVVKAVESLP-TTVSGKVDRK-------------
MGG_15097T0_1       ---------F-SRVLARLPLPQYMRPAAIFPIDNFP-TNASGKVDRIA------------
MGG_15248T0_1       ------------------------------------------------------------
MGG_12175T0_1       ------------------------------------------------------------
MGG_14967T0_3       ------------------------------------------------------------
MGG_15681T0_1       ------------------------------------------------------------
                                                                                

MGG_15682T0_1       --
MGG_14967T0_8       --
MGG_02611T0_2       --
MGG_14967T0_4       --
MGG_05025T0_2       --
MGG_09647T0_2       --
MGG_15248T0_2       --
MGG_14967T0_2       --
MGG_06199T0_2       --
MGG_08288T0_3       --
MGG_12175T0_6       --
MGG_14967T0_6       --
MGG_12175T0_4       --
MGG_07858T0_3       --
MGG_07803T0_2       --
MGG_02351T0_6       --
MGG_00022T0_2       --
MGG_12175T0_2       --
MGG_02351T0_10      --
MGG_07858T0_5       --
MGG_07858T0_7       --
MGG_14767T0_1       --
MGG_02351T0_4       --
MGG_02351T0_2       --
MGG_02351T0_8       --
MGG_00689T0_1       NV
MGG_09647T0_1       --
MGG_04646T0_1       --
MGG_14967T0_5       --
MGG_14967T0_1       --
MGG_03290T0_1       --
MGG_14967T0_7       --
MGG_02351T0_3       --
MGG_00022T0_1       --
MGG_07858T0_1       --
MGG_07858T0_4       --
MGG_07858T0_6       --
MGG_07858T0_2       --
MGG_02351T0_7       --
MGG_02351T0_1       --
MGG_02351T0_9       --
MGG_12175T0_3       --
MGG_00022T0_4       --
MGG_00022T0_3       --
MGG_00022T0_6       --
MGG_03810T0_1       --
MGG_08257T0_1       --
MGG_14897T0_1       --
MGG_09589T0_1       --
MGG_12175T0_5       --
MGG_12447T0_1       --
MGG_14943T0_1       --
MGG_15097T0_1       --
MGG_15248T0_1       --
MGG_12175T0_1       --
MGG_14967T0_3       --
MGG_15681T0_1       --
                      
