MUSCLE (3.8) multiple sequence alignment


MGG_07803       --YAIVGISCRFPGANTAE---QLWNVLME-----QRDAITTFCPAENLGFALEENSVFV
MGG_08281       -RIAVIGMGGRGPDSSANDGLDQFWEIIRE-----GRDVARKIPEER-----FNADGLFQ
MGG_013767      DDIAIIGMACRFPGDATNPS--RLWDLLMD-----GRSAWSPVPATR-----WNQDAHYH
MGG_08285       -PVAIIGMACRFPGEATNPC--KFWELLKE-----GKDAFSE--PDR-----FNASAFYH
MGG_12447       EPIAIIGSGCKFPGGSTTPS--KLWELLKD-----PKDIVSEIRPDR-----FDVDKYFH
MGG_09589       --IAVIGLANRFPGGADTPA--RLWTILKDAASAEAADLSREPPPGR-----MNLRKFYH
MGG_14897       EPVAIIGYSLRFPGGADTPS--KFWELLTS-----GRDISREPDPRR-----LNLSKFHH
                   *::* . . *.        .:* :: .       .               :    . 

MGG_07803       P----RYG-----------------------MI----DALKDFEPSAYSMSDAEAQTIDP
MGG_08281       TEAA-GAGLSSSSSSSSSSSSLCRSSTDYGCFL----RDPGHFDSRYFRLSPREASLLDP
MGG_013767      PSPE-HAG---------------SNVVKGGHFLRDGEQNGKQFDAAFFNIPRTETETMDL
MGG_08285       ANSSGRQN---------------VLPCKGAHFL---KGDPYAFDAAFFNMTPGEALASDP
MGG_12447       PDHK-HHG---------------TSNVRHSYFL---EENFKHFDAKFFGIRPQEAMAMDP
MGG_09589       PDGD-RHG---------------RTPVGKAYFLSE-DLDPALFDASFFGISPLEAEAMDP
MGG_14897       AKGE-HHG---------------SSNVLKSYFL---DQDPCLFDGSFFGISPLEAEAMDP
                .      .                       ::         *:   : :   *:   * 

MGG_07803       QKRVFLDVAADALADAGTSASPGNPLDPVGVFVGAAT--NTFLSSRDNPGSKPPGDEEPQ
MGG_08281       CSRLFLMAACEAVEMSGYSDGRSRSVHP-GRIGVVYGQSNEDGYMT----THHERGCDAY
MGG_013767      QQRVVMENVYEAMESAGLRLEDVKGSKT-SVFAGVFT--DDVRSIL----QEDPDLSVKY
MGG_08285       RQRLALEVAYEALENAGMTLQRVAGSRT-ACFVGAAANMAEYRDGI----VRDFGNQPQH
MGG_12447       QQRFLLETVYESLEAAGITISDLKGSQA-GVFVGNMG--VDYSELL----SQDIDAFPTY
MGG_09589       QQRMLLETVYEASESAGMPLDKLKAANC-AVYVGAMT--ADYAELP----TRDVEDVSTY
MGG_14897       QQRLLLETVYEAAESAGATLEGLRGSRT-SVHVGVMT--GDYADVQ----ARDAEDLSSY
                 .*. :  . ::   :*            .                              

MGG_07803       SFANHYQQLLDCPIGTFASFKLNLTGPVVTLNTACSSALAALHLACASLS----HGDCNA
MGG_08281       TLQTVQRAFAPGRVAHH----FGWEGPTWSVDSACSTSSSILHLATGMLA----AGEVDM
MGG_013767      KPIGTSAAILAARVSWF----YDLRGASFTLDTACSGSIVALHTGAQDLR----AGLSDM
MGG_08285       TIMGVSEELMSNRLSHF----FDLHGPSATVETACSSSLVAVHLACQSLR----LGESEM
MGG_12447       FAPGTARSILSNRISYF----FDLHGPSVTVDTACSSSLVAVHQAVQSLR----LGETPV
MGG_09589       MASGTSRAVLANRISHF----FDLRGPSVCLDTACSSSLVALHLACQDLR----TGCADM
MGG_14897       TASGTSRAMLANRVSYA----LDLRGPSVCIDTACSSSLVALHQAVRDLAAEGGAAGSDM
                        .    :.       .  *.   :::*** :   :* .   *      .    

MGG_07803       AVVGGVSMAYPQEGGYVTARPGGDSSAVFSPSGVCHPLDSRADGCVPADGAAALVIKRLA
MGG_08281       VVAGASNVISSPHGWCALSKSG-----VLSATGNCKPFRDDADGYCRGEFVGAVVLKRLE
MGG_013767      SIITGVNIIESPEFMFRASGLG-----MVSPDGKCYSLDSRANGYGRGEGVGTVILKPVW
MGG_08285       AVAGGVNLLLSPDTFMQLQNLS-----VLSPEGRSRSFDDEGRGYGRGEGCGIVVLKPLA
MGG_12447       AIVCGANLLLGPAQYIAESKLQ-----MLSPNGRSRMWDASADGYARGEGFASIVLKPLS
MGG_09589       AVVAGSCLILSPDMFISESKLH-----MLSPTGHCRMWDSSADGYARGEGAAALFLKPLS
MGG_14897       AIVAGCGLLLDPLMYIAESKLR-----MLSPTGTSKMWDAAADGYARGEGVAAVLLKPLS
                 :  .  :                   :.*. * .      . *   .:  . :.:* : 

MGG_07803       DARADGCRVYAVIEGVAVSADGSDDKAGLGVPSSSGQSRTVEAALRRAGPQAL---SRLR
MGG_08281       DAVAHHDQVLAVIAATGKNQSGN-AA-SITTPDAGAQERLFRRVLRTAGVAP----TDIS
MGG_013767      AAIRDGNVIRGVLRGTGVNSDGRGTG-GITLPNKAAQERLIRDVYSRNNLDT----DHTG
MGG_08285       AALRDGDPIRAVIRGTGSNSDGW-TK-GMAMPSGESQMHLIKDVYETFGLD---------
MGG_12447       VALANGDHIECIIRETGCNQDGR-TK-GITMPSPLAQCKLIQETYKRAGLDLSKSSDRPQ
MGG_09589       RALADGDPVHGVIRASGVNSDGR-TP-GITMPSYRAQARLIKDVYKSAGLNPLKPEDRCQ
MGG_14897       RALRDGDPIRGVVRATGVNSDGR-TP-GITMPSAEAQASLIWDTYRAAGLDPFNVEERCQ
                 *      :  ::   . . .*     .:  *.  .*   .  .    .           

MGG_07803       YVEMHGSGTPWGDALEVQGLKMAF------------------DRLSKTGAAEQSGTGRAQ
MGG_08281       YVEAHGTGTPVGDPCEMTAIAGALARPGSRGKGKGKGKGKGKGKGKGKGKGKGKGKGMGK
MGG_013767      FIEGHFTGTPAGDPTEASAIASVF-------------------------------QRGGP
MGG_08285       YAETHTIG--------------------------------------------------RA
MGG_12447       YFEAHGTGTPAGDPVEAEAISTAFFGPE--------------------------SGFRRT
MGG_09589       YFEAHGTGTQAGDPVEAHGVFDAFFSTESDGGEP--------DDFFSTGSHEVSDGRLED
MGG_14897       YFEAHGTGTPAGDPVEARGIFKSFFDPE-------------------------SAKKSRT
                : * *  *                                                    

MGG_07803       PEADRIYLGSNKGNCGNTEAASGLLSLIKASMALNLGVVPPLPNLAE-PNPKCEF--EET
MGG_08281       GEEERLVVGAVKANIGHSEAASGIASLIKGVFMFRHQLVPPQAGMPHTLNPRLLPLLDQA
MGG_013767      AAKPPLYVGAVKANIGHLEAASGMAQIIKTVLALENGVIPPNTNFEK-INPRIPI--ERW
MGG_08285       ARNQRLIMGSVKPNIGHLEPAAGIAGLIKGVLALERGLIPPNIHLNK-INRKIPL--DEW
MGG_12447       SHDPKLYVGSVKTVIGHTEGTAGLAGLIKASLAMKAKSIPPNLHLER-VNPAVQP--FYG
MGG_09589       DDGKQLLVGSIKTVLGHLEGCAGLAGIIKVLLAMKHGVVPPNKHFVK-LNPKIVQ--FSH
MGG_14897       SEETPLLVGSVKTIIGHLEGCAGLAGVIKVLVAMEHDTIPPNLHLKR-LNPEIEP--LSR
                     : :*: *   *: *  :*:  :**  . :    :**   :    *          

MGG_07803       KFE-------------PLGKQLALAPG-------------
MGG_08281       GIVIPSSTRLGAFESAPGRPRRILINNVDAAGGNACFLLE
MGG_013767      GLKLP--LVPTPFEPGPLGVRRASINSFGFGGTNAHVVI-
MGG_08285       NMEVPTRLTAWP----VTQQRPMSISSFGLGGTNAHVVM-
MGG_12447       NLEIPTRLMDWP-EPAPGQPLRASVNSFGFGGANAHVIL-
MGG_09589       RLRVPTEALAWPDPGGPGGTRRASVNSFGFGGTNAHVIVE
MGG_14897       VLKIPTESRPWP-TPAAGQPKRASVNSFGFGGTNAHAII-
                 :                        .             
